FROM python:3.14-slim-bookworm

ENV PYTHONUNBUFFERED=1
WORKDIR /app

COPY ../requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ../*.py .

# Default envs (override as needed)
ENV IQ_GENERATOR_URL=http://localhost:8000

EXPOSE 8080

CMD ["python", "audio_filter_analyzer.py"]
